config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get "/dashboard", to: "pages#dashboard", as: :dashboard
  get "parkingspaces/search", to: "parking_spaces#search", as: :search_parkingspace
  resources :parking_spaces do
    resources :bookings, only: [:new, :create, :show, :edit, :update] do
      resources :payments, only: [:new, :create]
    end
  end
  resources :cars
  resources :bookings, only: [:index]

end

app/models/parking_space.rb
class ParkingSpace < ApplicationRecord
  belongs_to :user
  has_many :bookings
  validates :size, presence: true
  validates :address, presence: true
  validates :city, presence: true
  validates :postcode, presence: true
  validates :country, presence: true
  validates :category, presence: true
  validates :price_per_hour, presence: true
  validates :user, presence: true
  geocoded_by :geocodedata
  after_validation :geocode

  def geocodedata
    "#{address}, #{postcode} #{city}, #{country}"
  end

end

app/controllers/parking_spaces_controller.rb
class ParkingSpacesController < ApplicationController
  before_action :set_parking_space, only: [:show, :update, :edit, :destroy]
  skip_before_action :authenticate_user!, only: [:search, :show]
  skip_after_action :verify_authorized, only: [:search, :show]

  def index
    @parking_spaces = policy_scope(ParkingSpace).order(created_at: :desc)
    @parking_spaces_data = []
    @parking_spaces.each do |space|
      @markers =
        {
          lat: space.latitude,
          lng: space.longitude
        }

      @parking_space_data = {
        markers: @markers,
        parking_space: space
      }
      @parking_spaces_data << @parking_space_data
    end
  end

  def show
    @marker = { lat: @parking_space.latitude, lng: @parking_space.longitude}
    @booking = Booking.new
    if current_user
      @licenses = current_user.get_licenses
    else
      @licenses = ["No cars - are you logged in correctly?"]
    end
    authorize @parking_space
  end

  def new
    @parking_space = ParkingSpace.new
    authorize @parking_space
    @user = current_user
  end

  def create
    @parking_space = ParkingSpace.new(parking_space_params)
    @user = current_user
    @parking_space.user = @user
    authorize @parking_space
    if @parking_space.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @user = current_user
  end

  def update
    authorize @parking_spaces
    @parking_space.update(parking_space_params)
    if @parking_space.update
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    authorize @parking_spaces
    @parking_space.destroy
    redirect_to root_path
  end

  def search
    if params[:cord].nil?
      result = Geocoder.search(params[:search][:query])
      @location = result.first.coordinates
    else
      @location = params[:cord].split(" ")
    end
    @parking_spaces = ParkingSpace.near(@location,1)
    if @parking_spaces.length == 0
      @markers =
        {
          lat: @location[0],
          lng: @location[1],
        }
      render :add_space
    else
      @markers = @parking_spaces.map do |space|
        {
          lat: space.latitude,
          lng: space.longitude,
          infoWindow: { content: render_to_string(partial: "/parking_spaces/map_box", locals: { space: space }) },
          icon: view_context.image_path("map-marker-black.png"),
        }
      end
    end
  end


  private

  def parking_space_params
    params.require(:parking_space).permit(:address, :postcode, :city, :country, :latitude, :longitude, :category, :availability, :size, :price_per_hour)
  end


  def set_parking_space
    @parking_space = ParkingSpace.find(params[:id])
  end

end

app/views/parking_spaces/_map_box.html.erb
<div class="map-box">
<%= space.address %>
<br>
<%= space.price_per_hour / 100.0 %>€ per hour
</div>

app/views/parking_spaces/add_space.html.erb
<div class="container">
  <div class="row">
    <div class="holder">
      <div class="noresult" data-aos="fade-down" data-aos-delay="750">
      <div class="parking-space-map-noresult">
        <div id="map_noresult" style="height: 100%; width: 100%" data-markers="<%= @markers.to_json %>"></div>
      </div>
      <div class="content-card-content">
        <h5> Sorry but parkwise is not yet available in your Area.</h5>
        <%= link_to "Go Back", root_path, class: "btn btn-primary no-result-back" %>
      </div>
      </div>
    </div>
  </div>
</div>

app/views/parking_spaces/edit.html.erb
<h2>Edit parking space located at @parking_space.address</h2>

<%= simple_form_for @parking_space do |f| %>
  <%= f.input :address %>
  <%= f.input :postcode %>
  <%= f.input :city %>
  <%= f.input :country, as: :text %>
  <%= f.input :latitude %>
  <%= f.input :longitude %>
  <%= f.input :category, as: :text %>
  <%= f.input :availability %>
  <%= f.input :size %>
  <%= f.input :price_per_hour %>

  <%= f.submit "Edit parking space", class: "btn btn-primary" %>
<% end %>

app/views/parking_spaces/index.html.erb
<div class="parking-container">
  <h1 class="my-parking-title"> Parking Spaces</h1>
  <div class="row" id="parking-maps-container">
    <% @parking_spaces_data.first(20).each_with_index do |parking_data, i|  %>
    <div class="col-xs-12 col-sm-12 col-md-6">
      <div class="card text-center">
        <div
        id="parking-map-<%= i %>"
        style="width: 100%; height: 200px;"
        class="parking-map"
        data-markers="<%= parking_data[:markers].to_json %>"
        ></div>
        <div class="card-body">
          <h5 class="card-title">
            <%= parking_data[:parking_space].address%>,
            <%= parking_data[:parking_space].city%>,
            <%= parking_data[:parking_space].postcode%>
          </h5>
          <p class="card-text">
            <strong>Category:</strong>
            <%= parking_data[:parking_space].category%>
            <br>
            <strong>Size:</strong>
            <%= parking_data[:parking_space].size%> meter(s)
            <br>
            <strong>Rate:</strong>
            €<%= parking_data[:parking_space].price_per_hour/ 100.00 %> per hour
          </p>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/parking_spaces/new.html.erb
    <div class="container">
      <div class="row">
        <div class="holder">
          <div class="content-card" data-aos="fade-down" data-aos-delay="750">
            <div class="content-card-content">
              <h2>Add a new parking space</h2>

              <%= simple_form_for @parking_space do |f| %>
                <%= f.input :address %>
                <%= f.input :postcode %>
                <%= f.input :city %>
                <%= f.input :country, as: :text %>
                <%= f.input :latitude %>
                <%= f.input :longitude %>
                <%= f.input :category, as: :text %>
                <%= f.input :availability %>
                <%= f.input :size %>
                <%= f.input :price_per_hour %>

                <%= f.submit "Add parking space", class: "btn btn-primary" %>
              <% end %>
           </div>
          </div>
        </div>
      </div>
    </div>

app/views/parking_spaces/search.html.erb
<div class="container-fluid">
  <div class="search-content">
    <div class="map-holder">
      <div id="map_search" style="height: 100vh; width: 50vw" data-markers="<%= @markers.to_json %>"></div>
    </div>
    <div class="card-holder">
      <% @parking_spaces.each_with_index do |space, index| %>
      <div class="card w-75 search-card" data-aos="fade-down" data-aos-offset="-75"
      data-aos-delay="<%= 100 + 400 * index < 2100 ? 100 + 400 * index : 150 %>">
        <div class="card-body">
          <h5 class="card-title"><%= space.address %></h5>
          <div class="card-icons">
            <div class="icons-left">
            <div>
            <i class="fas fa-parking"></i> <%= space.category %>
            </div>
            <br>
            <div>
            <i class="fas fa-square"></i> <%= space.size %>m³
            </div>
            </div>
            <div class="icons-right">
            <div>
            <i class="fas fa-money-bill-alt"></i> <%= space.price_per_hour / 100.00 %>€ per hour
            </div>
            <br>
            <div>
            <i class="fas fa-globe"> </i> <%= (space.distance_to(@location)*1000).round %>m away
            </div>
          </div>
          </div>
        </div>
        <div class="side-arrow">
          <div>
            <%= link_to "View >", parking_space_path(space), class: "side-arrow-link" %>
          </div>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/parking_spaces/show.html.erb
<div class="container-text-center-parking-space-show">
  <div class="grid-parking-space-show">

    <div class="parking-space-map-show">
      <div id="map_show" style="height: 100%; width: 100%" data-markers="<%= @marker.to_json %>"></div>
    </div>

    <div class="parking-space-picture-show">
      <div id="street-view" style="height: 100%; width: 100%" data-markers="<%= @marker.to_json %>"></div>
    </div>

    <div class="parking-space-show">
      <h2><%= @parking_space.address %>-</h2> <p class="price">Price Per Hour: <span id="booking-price"><%= @parking_space.price_per_hour / 100.00%></span>€</p>
      <p class="parking-space-details"><strong>Catagory:</strong> <%= @parking_space.category%> | <strong>Size:</strong> <%= @parking_space.size %> <strong>sqm</strong></p>
    </div>

    <div class="booking-parking-space-show">
      <strong><p>Book this parking space:</p></strong>
      <%= render 'bookings/new' %>
    </div>

  </div>
</div>