config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get "/dashboard", to: "pages#dashboard", as: :dashboard
  get "parkingspaces/search", to: "parking_spaces#search", as: :search_parkingspace
  resources :parking_spaces do
    resources :bookings, only: [:new, :create, :show, :edit, :update] do
      resources :payments, only: [:new, :create]
    end
  end
  resources :cars
  resources :bookings, only: [:index]

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-logo">
    <!-- FOOTER LOGO -->
  </div>
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <a class="navbar-brand" href="<%= root_path %>">
    Parkwise
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <% if user_signed_in? %>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="<%= root_path %>">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= cars_path %>">Cars</a>
      </li>
      <li class="nav-item">
        <% if current_user.parking_spaces.count > 0 %>
        <a class="nav-link" href="<%= parking_spaces_path %>">Parking Spaces</a>
        <% else %>
        <a class="nav-link" href="<%= new_parking_space_path %>">Add a Parking Spaces</a>
        <% end %>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= bookings_path %>">Bookings</a>
      </li>
    </ul>
    <ul class="navbar-nav">
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= image_tag current_user.avatar, class: "avatar" %>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to destroy_user_session_path, method: :delete, class: "dropdown-item" do %>
          Log out
          <% end %>
          <a class="dropdown-item" href="<%= dashboard_path %>">Dashboard</a>
          <a class="dropdown-item" href="#">Account Settings</a>
        </div>
      </li>
    </ul>
  </div>
  <% else %>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="<%= root_path %>">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= new_user_session_path %>">Log in</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= new_user_registration_path %>">Sign up</a>
      </li>
    </ul>
  </div>
  <% end %>
</nav>