config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get "/dashboard", to: "pages#dashboard", as: :dashboard
  get "parkingspaces/search", to: "parking_spaces#search", as: :search_parkingspace
  resources :parking_spaces do
    resources :bookings, only: [:new, :create, :show, :edit, :update] do
      resources :payments, only: [:new, :create]
    end
  end
  resources :cars
  resources :bookings, only: [:index]

end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
 before_action :set_booking
 skip_after_action :verify_authorized

  def new
  end

  def create
    customer = Stripe::Customer.create(
    source: params[:stripeToken],
    email:  params[:stripeEmail]
    )

    charge = Stripe::Charge.create(
    customer:     customer.id,   # You should store this customer id and re-use it.
    amount:       @booking.price,
    description:  "Payment for your Parkwise Parking Space",
    currency:     "eur"
    )
    @booking.update(payment: charge.to_json, status: 'paid')
    redirect_to bookings_path
    account_sid = ENV['TWILIO_SID']
    auth_token = ENV['TWILIO_AUTH_TOKEN']
    @client = Twilio::REST::Client.new(account_sid, auth_token)
    message = @client.messages.create(
                                     from: 'whatsapp:+14155238886',
                                     body: "Thank you for booking a parking place with Parkwise. The location of your Parking space is https://www.google.com/maps/search/?api=1&query=#{@booking.parking_space.latitude},#{@booking.parking_space.longitude}",
                                     to: 'whatsapp:+4915158581723'
                                   )
    message.sid
    rescue Stripe::CardError => e
      flash[:alert] = e.message
      redirect_to new_booking_payment_path(@booking.parking_space, @booking)
    end

private

  def set_booking
    @booking = current_user.car_bookings.where(status: 'pending').find(params[:booking_id])
  end

end

app/views/payments/new.html.erb
    <div class="container">
      <div class="row">
        <div class="holder">
          <div class="content-card" data-aos="fade-down" data-aos-delay="750">
            <div class="content-card-content">
              <%= form_tag parking_space_booking_payments_path(@booking.parking_space, @booking) do %>

                <table class="table">
                  <thead class="thead-dark">
                    <tr>
                      <th scope="col">Parking Spot</th>
                      <th scope="col">Duration</th>
                      <th scope="col">Amount</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <td><%= @booking.parking_space.address %></td>
                      <td><%= (@booking.end_time - @booking.start_time) / (60*60) %> hours</td>
                      <td><%= (@booking.price / 100.00).round(2) %>€</td>
                    </tr>
                  </tbody>
                </table>

                <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                  data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                  data-name="Parking Space"
                  data-email="<%= current_user.email %>"
                  data-description="Parking Space: <%= @booking.parking_space.address %>"
                  data-amount="<%= @booking.price %>"
                  data-currency="EUR"></script>

              <% end %>

           </div>
          </div>
        </div>
      </div>
    </div>