config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get "/dashboard", to: "pages#dashboard", as: :dashboard
  get "parkingspaces/search", to: "parking_spaces#search", as: :search_parkingspace
  resources :parking_spaces do
    resources :bookings, only: [:new, :create, :show, :edit, :update] do
      resources :payments, only: [:new, :create]
    end
  end
  resources :cars
  resources :bookings, only: [:index]

end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :user
  has_many :bookings
  validates :license , uniqueness: true
  validates :user, :license, :brand, :model, presence: true
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [:show, :update, :edit, :destroy]

  def index
    @cars = policy_scope(Car).order(created_at: :desc)
  end

  def new
     @car = Car.new
     authorize @car
  end

  def create
    @car = Car.new(car_params)
    @car.user = current_user
    authorize @car
    if @car.save
      redirect_to cars_path(current_user)
    else
      render :new
    end
  end

  def edit
    authorize @car
     #render
  end

  def update
    authorize @car
    @car.update(car_params)
    redirect_to cars_path(current_user)
  end

  def destroy
    authorize @car
    @car.destroy
    user = @car.user
    redirect_to cars_path(current_user)
  end

  private

  def set_car
    @car = Car.find(params[:id])
  end

  def car_params
    params.require(:car).permit(:license, :brand, :model, :colour)
  end
end

app/views/cars/edit.html.erb
<h1>Edit Car</h1>
 <%= simple_form_for(@car) do |f| %>
  <div class="form-group">
    <%= f.label :license %>
    <%= f.text_field :license, class: 'form-control' %>
  </div>
   <div class="form-group">
    <%= f.label :brand %>
    <%= f.text_field :brand, class: 'form-control' %>
  </div>
   <div class="form-group">
    <%= f.label :model %>
    <%= f.text_field :model, class: 'form-control' %>
  </div>
   <div class="form-group">
    <%= f.label :colour %>
    <%= f.text_field :colour, class: 'form-control' %>
  </div>
   <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/cars/index.html.erb
<div class="cars-cards">
  <h1>Cars</h1>
  <table class="cars-table" style="width: 100%">
  <tr>
    <th>License</th>
    <th>Brand</th>
    <th>Model</th>
    <th>Colour</th>
  </tr>

  <% @cars.each do |car| %>
  <tr>
    <td> <%= car.license %> </td>
    <td> <%= car.brand %> </td>
    <td> <%= car.model %> </td>
    <td> <%= car.colour %> </td>
    <% if policy(car).destroy? %>
    <td class="link"> <%= link_to "Delete", car_path(car), method: :delete, data: {confirm: "Are you sure?" } %> </td>
    <% end %>
    <% if policy(car).edit? %>
    <td class="link"> <%= link_to "Edit", edit_car_path(car) %> </td>
    <% end %>
  <% end %>
  </tr>
  </table>
  <br>
  <% if policy(@cars).create? %>
  <strong><%= link_to "Add new car", new_car_path %></strong>
  <% end %>
</div>

app/views/cars/new.html.erb
<h1>Add New Car</h1>
 <%= simple_form_for @car do |f| %>
  <div class="form-group">
    <%= f.label :license %>
    <%= f.text_field :license, class: 'form-control' %>
  </div>
   <div class="form-group">
    <%= f.label :brand %>
    <%= f.text_field :brand, class: 'form-control' %>
  </div>
   <div class="form-group">
    <%= f.label :model %>
    <%= f.text_field :model, class: 'form-control' %>
  </div>
   <div class="form-group">
    <%= f.label :colour %>
    <%= f.text_field :colour, class: 'form-control' %>
  </div>
   <%= f.submit class: 'btn btn-primary' %>
<% end %>